name: Simple CI

on:
  push:
    branches: [ main, develop, simplification ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Suite
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0'
    
    - name: Install jemalloc
      run: brew install jemalloc
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build
      run: swift build
    
    - name: Run Tests
      run: |
        swift test --parallel
    
    - name: Test Summary
      if: always()
      run: |
        echo "=== Test Execution Summary ==="
        echo "Test files: $(find Tests -name '*.swift' | wc -l)"
        echo "Test methods: $(grep -r 'func test' Tests --include='*.swift' | wc -l)"
        echo "Source files: $(find Sources -name '*.swift' | wc -l)"